name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
          - os: macos-latest
            libcxx: libc++
          - os: ubuntu-latest
            libcxx: libstdc++11
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: CMake configure
        if: ${{ contains(matrix.os, 'windows') }}
        run:
          cmake -B ${{github.workspace}}/build

      - name: CMake configure
        if: ${{ !contains(matrix.os, 'windows') }}
        run:
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: build
        run:
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: bench
        working-directory: ${{github.workspace}}/build
        run:
          ./bench